- Cargo.toml
Upstream bitflags now supports no_std as a feature so switch to that.
Signed-off-by: Doug Goldstein <cardoe@cardoe.com>
> depend: update to upstream bitflags release

- src/boot_loader_name.rs
- src/lib.rs
This was low-hanging fruit, since the tag has a simple structure and the payload is specified to be valid UTF-8.
> Add bootloader name tag

- .gitignore
- src/header.rs
- src/lib.rs
- src/module.rs
Why I was originally wary about creating ModuleIter is because I
have to make Tag and TagIter public so that it can work. I can
change this (by practically rewriting TagIter in ModuleIter), but
I think that this works fine (issue/comment if you feel otherwise).
I also made a very small change to .gitignore so that I would not
accidentally commit my .swp files.
> Added ModuleIter, .gitignore change

- src/boot_loader_name.rs
This is the same method I use to get the name in
`src/module.rs`, now neither return null characters.
> Fix #11:  BootLoaderNameTag returning null char

- src/elf_sections.rs
When using a higher half kernel the cast to u32 will tuncate the
section address which will return an incorrect elf section reference
to the caller. This is fixed by casting instead to a u64.
> Replace overflowing cast in src/elf_sections.rs

- src/memory_map.rs
This commit makes it so that pointers in `src/memory_map.rs` are casted only to other pointers and all arithmatic is done with the pointer `offset()` method.
> Prevent overflow in `src/memory_map.rs`

- src/lib.rs
I missed this when pushing the commit, StringTable should be
pub so that the desired functionality of "get your own String
Table and change the address" can work.
I know that this changes the public interface, sorry for opening
it so soon after the release.
> Make StringTable public

- src/command_line.rs
- src/lib.rs
This is just a copy of the boot loader name tag code, but for the command line tag (type = 1).
> Add the command line tag

- Cargo.toml
- src/elf_sections.rs
I'm following your guide, but instead I'm making a 32-bit kernel which uses ELF32 files. I added a new feature, `elf32`, which tweaks `ElfSections` to match this standard.
(I know, the project is called multiboot-elf64. But this doesn't hurt and helps a lot :-) )
> Add support for ELF32 format

- src/elf_sections.rs
- src/lib.rs
- src/memory_map.rs
- src/module.rs
This hides the implementation enough to allow supporting higher memory kernels.
> Change pub fields into functions.

- src/memory_map.rs
Hey thanks for the great OS series!
MemoryMapIter is used in the AreaFrameAllocator, which I want to put inside a Mutex and make global. I want to access it in syscalls. To be put inside a Mutex, it has to be `Send`.
> Make MemoryMapIter be Send

- Cargo.toml
- src/elf_sections.rs
- src/lib.rs
WIP: don't merge.
This is sort of a hacked up runtime implementation of ELF-32 support, primarily so @jmi2k can take a look and see if it works and satisfies their requirements.
I'm planning other changes that will make this much cleaner, but they're not ready yet.
> Detect ELF-32 at runtime, rather than compile time.

- Cargo.toml
- src/elf_sections.rs
- src/lib.rs
Note, this is technically a breaking change but I'd say it's a good one given that it results in using a stable version of bitflags.
> Update to the 1.0.0 version of bitflags.

- src/elf_sections.rs
@jmi2k @robert-w-gries 
The current code mostly assumes that you're reading ELF headers which match the size of your platform, due to the use of `usize`. That means that the code is always memory safe but potentially truncating data. This proposes always returning `u64` and promoting all `u32` types to that, which means you always get all of the data.
What do you think?
> Use u64, even on 32-bit to support reading elf-64 files.

- src/elf_sections.rs
- src/header.rs
- src/lib.rs
- src/module.rs
Add debug implementations.
Mark everything as repr(C) and repr(packed), just to be sure.
> Various cleanups.

- src/elf_sections.rs
Fix the following warning before it becomes a hard error:
```
warning: the type of this value must be known in this context
--> src/elf_sections.rs:11:43
|
11 |         inner: unsafe { (tag as *const _).offset(1) } as *const _,
|                                           ^^^^^^
|
= note: #[warn(tyvar_behind_raw_pointer)] on by default
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= note: for more information, see issue #46906 <https://github.com/rust-lang/rust/issues/46906>
```
> Resolve tyvar_behind_raw_pointer warning

- README.md
After moving the repository under `rust-osdev`, we need to update the pointer to the Travis build status
> Fix travis badge in README

- src/lib.rs
- src/rsdp.rs
This adds support for tags for reading the address of the RSDP, a structure used in ACPI. There are two different structs, one for ACPI Version 1.0, the other for subsequent versions. It also adds tests to the grub2 test.
> Add support for RSDP tags

- src/framebuffer.rs
- src/lib.rs
Adds the `BootInformation::framebuffer_tag` function along with associated structs, for framebuffer information as well as color data.
> Add Framebuffer Tag

- Cargo.toml
This bumps the version, after which I will publish the new version, as suggested in [#46 (comment)](https://github.com/rust-osdev/multiboot2-elf64/pull/46#issuecomment-397557208)
Could I get a review from someone please @rust-osdev/multiboot2
> Multiboot2 0.6.0

- Cargo.toml
- src/memory_map.rs
Fixes #49 
Note: This is a breaking change.
> Return memory_map entries as u64, to support 32-bit targets

- Cargo.toml
- src/memory_map.rs
- src/rsdp.rs
Looks like I was a bit hasty merging #50 and missed that we're still returning a `usize` from the `size` method. I've also bumped the version to `0.7.1` from `0.7.0`, as this only patches the previous breaking change.
@rust-osdev/multiboot2 could I get a review so I can publish the new version (`0.7.0` is already published, it'd be good to minimise the number of people who upgrade and have to work around this)
> Return u64 from MemoryArea::size as well

- src/elf_sections.rs
Adds an addralign() function to `ElfSection`, which returns the alignment of that section.
> Allow users to read elf section alignment

- src/framebuffer.rs
- src/header.rs
- src/lib.rs
- src/memory_map.rs
- src/module.rs
Redid PR #31.
The code builds and passes all automated tests of the repo, but I didn’t test it using another project or similar. The many unsafe blocks doing pointer dereferencing and such hide stuff from the lifetime-checker. So simply because it builds is not yet assuring to me. Please check and test before merging.
I made an API change to `TagIter`, requiring the use of a constructor function.
I am sure that I haven’t captured the intention of issue #22 completely. Although, all handed-out references have some parametric lifetime, this patch doesn’t improve “safety”. Meaning: out-of-bounds accesses aren’t prevented and the multiboot2 header can’t be at an arbitrary place in memory, because the physical addresses inside the header are still directly interpreted as pointers.
> Use no `'static` lifetimes anymore

- Cargo.toml
This includes the changes from #57.
@rust-osdev/multiboot2 could I get a review here, after which I'll publish the changes to crates.io
> Publish v0.8.0

- src/framebuffer.rs
- src/lib.rs
- src/vbe_info.rs
This adds `VBEInfoTag` and friends in a new module `vbe_info` and a test for this, as well as fixing a few bugs in the implementation of `FramebufferTag` and adding a new method `current_address()` to `Reader`.
> Fix bugs in FramebufferTag, add VBEInfoTag.

- src/boot_loader_name.rs
- src/command_line.rs
- src/elf_sections.rs
- src/framebuffer.rs
- src/lib.rs
- src/memory_map.rs
- src/module.rs
- src/rsdp.rs
- src/vbe_info.rs
I've started an attempt at solving #40 
Currently this PR introduces a crate level `deny(missing_docs)` and attempts at least a single line of documentation for every publicly visible item.
It's not much but its better than nothing and over time I aim to add more sections covering examples and unsafe notices.
> Add some basic documentation

- src/lib.rs
- src/rsdp.rs
Add the validate_checksum method to the implementation of the RsdpV1Tag
and RsdpV2Tag.
CC: @phil-opp @IsaacWoods 
Fixes: #63
> rsdp: add the validate_checksum to rsdp

- README.md
- src/lib.rs
- src/memory_map.rs
- src/rsdp.rs
Fix #30 
[Multiboot 2.0](https://www.gnu.org/software/grub/manual/multiboot2/multiboot.html)
TODO:
> Add support for multiboot2.

- src/elf_sections.rs
- src/framebuffer.rs
- src/lib.rs
- src/module.rs
- src/rsdp.rs
Close #38.
We occasionally use`repr(packed)` when the struct is unaligned. When we use it, I added a comment explaining why. In addition, we derive `Copy` and `Clone` to allow the compiler to copy the fields to locals.
> Improve usage of repr(packed)

- src/memory_map.rs
https://github.com/rust-osdev/multiboot2-elf64/issues/70
> Access to non-available memory areas 

- src/elf_sections.rs
- src/lib.rs
- src/memory_map.rs
Two return types are mixed so all return types are integrated to `impl
Iterator`.
> chore: use `impl Iterator`

- Cargo.toml
- src/lib.rs
The previous version of the `asm!` macro is renamed to `llvm_asm!`. It will not be stable.
> fix(docs): remove a code example in the top page of the doc

- src/elf_sections.rs
- src/header.rs
- src/lib.rs
- src/module.rs
The current debug output of the BootInformation-struct is not optimal. It isn't nicely formatted (no spaces), doesn't include all relevant fields (like UEFI system table tag) and it outputs all ELF-sections, which can be pretty fast thousands of lines with pretty much useless output. 
What do you think about my improvement?
POC with my multiboot2 Rust kernel in QEMU:
```
Multiboot2 Boot Information {
start_address: 0x0000000000597000,
end_address: 0x00000000005e9ae0,
total_size: 0x0000000000052ae0,
boot_loader_name_tag: "GRUB 2.04-1ubuntu44.2",
command_line: "",
memory_areas: None,
module_tags (count): 0,
elf_sections_tags (count): 5287,
efi_32_ih: None,
efi_64_ih: Some(
EFIImageHandle64 {
typ: 20,
size: 16,
pointer: 114517528,
},
),
efi_sdt_32_tag: None,
efi_sdt_64_tag: Some(
EFISdt64 { …
```
> much improved debug output of BootInformation + enum TagType

- src/header.rs
- src/lib.rs
To my surprise the multiboot2 magic number is not yet available inside the crate. In my Rust kernel I currently have a hard-coded constant. I think it would be beneficial, if we upstream this into the crate.
> add multiboot2 magic number

- src/header.rs
- src/lib.rs
In the multiboot2 spec the constant is named `MULTIBOOT2_BOOTLOADER_MAGIC`. I think we should rename it (the current one is not released yet, therefore not breaking). Eventually we have the two constants `MULTIBOOT2_BOOTLOADER_MAGIC` and `MULTIBOOT2_HEADER_MAGIC` (#79)
> renamed multiboot2 bootloader magic constant

- Cargo.toml
- Changelog.md
- README.md
- src/lib.rs
Hey @IsaacWoods 
what do you think? If we are ready to go, we can merge this and afterwards focus on #86 
- adjusted Cargo.toml
- adjusted lib.rs documentation
- adjusted README
- adjusted Changelog
> Cargo toml prepare relase v0.12 + changelog

- src/module.rs
Merge after #89 
This PR fixed a wrong description in the ModuleTag. I tested and verified my change in with GRUB in QEMU.
> Fix ModuleTag cmdline

- .github/workflows/rust.yml
- .travis.yml
- src/header.rs
- src/lib.rs
- src/memory_map.rs
- src/module.rs
- src/rsdp.rs
- src/vbe_info.rs
- add clippy check as required
- add rustfmt check as required
- add rustdoc check as required (`#![deny(rustdoc::all)]` works since stable 1.52.0)
To improve and enforce code quality.
I'm not sure if we still use Travis CI. 
What's your opinion on this @Caduser2020  @IsaacWoods ?
> Code style improvements + optional CI job (clippy, rustfmt, rustdoc)

- .editorconfig
- Changelog.md
This change doesn't change the formatting of existing code, but makes sure all IDEs with support for this (VIM, Jetbrains IDEs, VS Code) use the same spacing style that `rustfmt` also uses by default. This makes a `cargo fmt` needless in most cases.
> Editorconfig file.

- multiboot2/Cargo.toml
- multiboot2/Changelog.md
- multiboot2/src/header.rs
- multiboot2/src/lib.rs
This crate now supports `std` in tests but is still `no_std` itself. `TagType` implements now `Hash` so that it can be used in `HashSet`. This is a requirement for the upcoming release of `multiboot2-header`.
> multiboot2 v0.12.2 (std in tests; hash for TagType)

- multiboot2/Changelog.md
I noticed that in PR #72 a change was made which is a breaking change, but was not mentioned as such in the changelog. Updated changelog to reflect this.
> Updated 12.0 changelog to note breaking change to iterators

- multiboot2-header/Cargo.toml
- multiboot2-header/README.md
- multiboot2-header/src/address.rs
- multiboot2-header/src/console.rs
- multiboot2-header/src/end.rs
- multiboot2-header/src/entry_efi_32.rs
- multiboot2-header/src/entry_efi_64.rs
- multiboot2-header/src/entry_header.rs
- multiboot2-header/src/framebuffer.rs
- multiboot2-header/src/header/builder.rs
- multiboot2-header/src/header/mod.rs
- multiboot2-header/src/information_request.rs
- multiboot2-header/src/lib.rs
- multiboot2-header/src/module_alignment.rs
- multiboot2-header/src/relocatable.rs
- multiboot2-header/src/uefi_bs.rs
When I initially released this, I have overseen that this referenced `std`. This PR enables the crate in `no_std`-contexts and enables to disable the new `builder`-feature. When the latter is not included, the crate also does not need `alloc`.
This fixes #98 . #101  will ensure that such problems will not occur in the future.
This bumps the version to `v0.1.1`
> multiboot2-header: fix `no_std`-build + v0.1.1

- .editorconfig
- .github/workflows/rust.yml
Currently, the CI does not check if this actually builds with `no_std`. This MR fixes this.
After #98 is fixed, this should be mandatory for all new MRs
> repo: add CI no_std check

- multiboot2-header/README.md
- multiboot2-header/src/information_request.rs
- multiboot2-header/src/lib.rs
- multiboot2/README.md
- multiboot2/src/lib.rs
I think this is relevant information that should be announced officially. This also helps us to identify breaking changes when we introduce new Rust functionality.
> publicly announce the MSRV is 1.52.1.

- multiboot2-header/README.md
- multiboot2-header/examples/minimal.rs
- multiboot2-header/src/address.rs
- multiboot2-header/src/builder/header.rs
- multiboot2-header/src/builder/information_request.rs
- multiboot2-header/src/builder/mod.rs
- multiboot2-header/src/builder/traits.rs
- multiboot2-header/src/console.rs
- multiboot2-header/src/end.rs
- multiboot2-header/src/entry_efi_32.rs
- multiboot2-header/src/entry_efi_64.rs
- multiboot2-header/src/entry_header.rs
- multiboot2-header/src/framebuffer.rs
- multiboot2-header/src/header.rs
- multiboot2-header/src/information_request.rs
- multiboot2-header/src/lib.rs
- multiboot2-header/src/module_alignment.rs
- multiboot2-header/src/relocatable.rs
- multiboot2-header/src/uefi_bs.rs
- restructures code of `multiboot2-header` so that all builder-related code is inside the new `builder`-module
- minor breaking changes (changed paths for two structs)
-> this is fine because so far the crate is rarely used
> Multiboot2 header builder restructuring

- multiboot2-header/Cargo.toml
- multiboot2-header/Changelog.md
Prepares release v0.2.0 for `multiboot2-header`-crate
Blockers:
> multiboot2-header: prepare v0.2.0

- multiboot2/src/lib.rs
`BootInformation` does not mutate the multiboot information it points to. Furthermore, by creating regular references to the contained data, it implicitly assumes it is not mutated elsewhere. With these assumptions in place it is safe to `impl Send for BootInformation`.
This PR adds the `Send` impl and clarifies safety contracts for clients.
> Add Send impl for BootInformation

- multiboot2/Cargo.toml
- multiboot2/Changelog.md
- multiboot2/src/boot_loader_name.rs
- multiboot2/src/command_line.rs
- multiboot2/src/elf_sections.rs
- multiboot2/src/framebuffer.rs
- multiboot2/src/lib.rs
- multiboot2/src/module.rs
- multiboot2/src/rsdp.rs
- multiboot2/src/vbe_info.rs
Improve safety when parsing strings from Tags + general code improvements.
> Multiboot2: More Safety for Getters of Strings from Tags (Prepare Release v0.14.0)

- multiboot2-header/src/builder/information_request.rs
- multiboot2-header/src/header.rs
- multiboot2/src/lib.rs
- multiboot2/src/memory_map.rs
Correct EFI 'last_area' calculation and align it to be more similar the E820 version.
(Previously, iterating the EFI Memory map resulted in a superfluous entry as it ran over the next tag)
> multiboot2: Fix EFI Memory Map 'last_area' calculation

- .github/workflows/rust.yml
- multiboot2-header/src/builder/information_request.rs
- multiboot2-header/src/header.rs
- multiboot2/Cargo.toml
- multiboot2/Changelog.md
- multiboot2/src/framebuffer.rs
- multiboot2/src/vbe_info.rs
This will merge #119 plus a few commits by myself into main.
The cargo.toml and the changelog are prepared for the 0.14.1 release.
> Merge #119 + necessary fixed into main + multiboot2-0.14.1

- .editorconfig
- .github/workflows/qa.yml
- .github/workflows/rust.yml
- .typos.toml
- Cargo.toml
- multiboot2-header/src/builder/traits.rs
- multiboot2/Cargo.toml
- multiboot2/Changelog.md
- multiboot2/src/boot_loader_name.rs
- multiboot2/src/command_line.rs
- multiboot2/src/elf_sections.rs
- multiboot2/src/lib.rs
- multiboot2/src/rsdp.rs
- multiboot2/src/vbe_info.rs
- prepare 0.14.2
- documentation fixes
- add unstable feature
> Multiboot2 v0.14.2 dev

- .github/workflows/_build-rust.yml
- .github/workflows/rust.yml
cache per rust version. This is necessary to make the Rust cache effective. 
CI is now super cool, fast, and wonderfully over-engineered and still nice 😄
> ci: cache per rust version

- .github/workflows/_build-rust.yml
- .github/workflows/rust.yml
- multiboot2-header/Cargo.toml
- multiboot2-header/Changelog.md
- multiboot2-header/README.md
- multiboot2-header/src/builder/information_request.rs
- multiboot2-header/src/lib.rs
- multiboot2/Cargo.toml
- multiboot2/Changelog.md
- multiboot2/README.md
- multiboot2/src/boot_loader_name.rs
- multiboot2/src/command_line.rs
- multiboot2/src/efi.rs
- multiboot2/src/elf_sections.rs
- multiboot2/src/framebuffer.rs
- multiboot2/src/image_load_addr.rs
- multiboot2/src/lib.rs
- multiboot2/src/memory_map.rs
- multiboot2/src/module.rs
- multiboot2/src/rsdp.rs
- multiboot2/src/tag_type.rs
- multiboot2/src/vbe_info.rs
This bumps multiboot2 to v0.15.
> multiboot2-v0.15

- .github/workflows/_build-rust.yml
- .github/workflows/rust.yml
With this, we ensure that developers can develop Multiboot2 applications using this lib also on Windows.
> ci: windows

- multiboot2-header/src/builder/header.rs
- multiboot2-header/src/relocatable.rs
- multiboot2/Cargo.toml
- multiboot2/src/boot_loader_name.rs
- multiboot2/src/builder/information.rs
- multiboot2/src/builder/mod.rs
- multiboot2/src/builder/traits.rs
- multiboot2/src/command_line.rs
- multiboot2/src/efi.rs
- multiboot2/src/elf_sections.rs
- multiboot2/src/framebuffer.rs
- multiboot2/src/image_load_addr.rs
- multiboot2/src/lib.rs
- multiboot2/src/memory_map.rs
- multiboot2/src/module.rs
- multiboot2/src/rsdp.rs
- multiboot2/src/smbios.rs
- multiboot2/src/tag_type.rs
Hey, I'm currently working on adding Multiboot 2 support to a bootloader ([towboot](https://github.com/hhuOS/towboot)) and while using the multiboot2 and multiboot2-header crates, I encountered some pieces that were missing.
I particular:
* I added more getters to multiboot2-header (mostly inspired by the ones in multiboot2).
* I added a builder to multiboot2 (inspired by multiboot2-header).
* I added the SMBIOS tag.
* I added a function to find a header in a given (file) slice.
This is mostly just boilerplate, but there were two bigger problems I had to work around:
1) The memory map is only really accurate after exiting Boot Services, but then the bootloader can't allocate anymore.
I've solved this by prefilling the memory map tags with empty entries and overwriting them later on. It …
> Add a builder to multiboot2

- multiboot2-header/src/address.rs
- multiboot2-header/src/builder/header.rs
- multiboot2-header/src/builder/information_request.rs
- multiboot2-header/src/console.rs
- multiboot2-header/src/end.rs
- multiboot2-header/src/entry_address.rs
- multiboot2-header/src/entry_efi_32.rs
- multiboot2-header/src/entry_efi_64.rs
- multiboot2-header/src/framebuffer.rs
- multiboot2-header/src/header.rs
- multiboot2-header/src/information_request.rs
- multiboot2-header/src/module_align.rs
- multiboot2-header/src/relocatable.rs
- multiboot2-header/src/tags.rs
- multiboot2-header/src/uefi_bs.rs
- multiboot2/src/boot_loader_name.rs
- multiboot2/src/builder/information.rs
- multiboot2/src/command_line.rs
- multiboot2/src/efi.rs
- multiboot2/src/elf_sections.rs
- multiboot2/src/framebuffer.rs
- multiboot2/src/image_load_addr.rs
- multiboot2/src/lib.rs
- multiboot2/src/memory_map.rs
- multiboot2/src/module.rs
- multiboot2/src/rsdp.rs
- multiboot2/src/smbios.rs
- multiboot2/src/tag_type.rs
- multiboot2/src/vbe_info.rs
- streamline default derives
- removed packed where it is not needed (because the default C representation is already packed)
> streamline default derives

- multiboot2-header/src/address.rs
- multiboot2-header/src/console.rs
- multiboot2-header/src/end.rs
- multiboot2-header/src/entry_address.rs
- multiboot2-header/src/entry_efi_32.rs
- multiboot2-header/src/entry_efi_64.rs
- multiboot2-header/src/framebuffer.rs
- multiboot2-header/src/header.rs
- multiboot2-header/src/information_request.rs
- multiboot2-header/src/module_align.rs
- multiboot2-header/src/relocatable.rs
- multiboot2-header/src/tags.rs
- multiboot2-header/src/uefi_bs.rs
- multiboot2/src/boot_loader_name.rs
- multiboot2/src/command_line.rs
- multiboot2/src/efi.rs
- multiboot2/src/elf_sections.rs
- multiboot2/src/framebuffer.rs
- multiboot2/src/image_load_addr.rs
- multiboot2/src/memory_map.rs
- multiboot2/src/module.rs
- multiboot2/src/rsdp.rs
- multiboot2/src/smbios.rs
- multiboot2/src/vbe_info.rs
This doesn't have a big negative impact but gives library users more freedom.
> tree-wide: streamline default derives (also Hash everywhere)

- multiboot2/Changelog.md
- multiboot2/src/lib.rs
- multiboot2/src/memory_map.rs
Via git-bisecting, I could find that https://github.com/rust-osdev/multiboot2/commit/d198dceffe544b6324ba4c204270d9a1d934abba broke something with the (legacy) memory map tag. This MR fixes the problem and adds a unit test for it.
Also see: https://github.com/rust-osdev/multiboot2/pull/133
> fix memory issue in memory-map

- Cargo.lock
- multiboot2/Cargo.toml
- multiboot2/Changelog.md
- multiboot2/src/builder/information.rs
- multiboot2/src/efi.rs
- multiboot2/src/image_load_addr.rs
- multiboot2/src/lib.rs
- multiboot2/src/memory_map.rs
- memory-map: derive Eq + uefi-raw@0.3.0
- `ImageLoadPhysAddr` -> `ImageLoadPhysAddrTag`
- `EFIImageHandle32` -> `EFIImageHandle32Tag`
- `EFIImageHandle32` -> `EFIImageHandle64Tag`
Now, all tags do end with "Tag" -> consistency
> multiboot2: memory-map: derive Eq + uefi-raw@0.3.0

- multiboot2/src/builder/mod.rs
This fixes multiple memory issues (wrong allocation and wrong fat pointer creation) that were introduced in #133 with 544e1ca555fb740eea272b936a41672eeef4d1ce.
I found the issues by running miri.
> multiboot2: fix memory issue in boxed_dst_tag

- multiboot2/src/builder/information.rs
- multiboot2/src/lib.rs
- multiboot2/src/tag_type.rs
This is an improvement that enables better memory checks by miri. Furthermore, it is technically the right way to model this in Rust.
Hopefully, eventually, this will also simplify #128 #117 
This change is entirely internal, and it won't add more breaking changes to the next release.
> multiboot2: model MBI as DST

- multiboot2/Changelog.md
- multiboot2/src/boot_loader_name.rs
- multiboot2/src/builder/information.rs
- multiboot2/src/builder/mod.rs
- multiboot2/src/command_line.rs
- multiboot2/src/lib.rs
- multiboot2/src/module.rs
Regarding 9cf763014624003044a2a406e0c497fb613a27e4:
I don't exactly understand why, but running this in the integration test
revealed a different behaviour compared to the unit test. In the unit test
environment, it always seemed like the next multiple of 8 is used for each
allocation as size. In the integration test, I did not encounter this. I
don't know what's the best solution here. Probably, just don't be too 
strict.
> various fixes

- multiboot2-header/src/builder/header.rs
- multiboot2/src/boot_loader_name.rs
- multiboot2/src/builder/information.rs
- multiboot2/src/builder/mod.rs
- multiboot2/src/command_line.rs
- multiboot2/src/elf_sections.rs
- multiboot2/src/framebuffer.rs
- multiboot2/src/memory_map.rs
- multiboot2/src/module.rs
- multiboot2/src/smbios.rs
There where more memory issues (according to miri) in the boxed_dst_tag function. I tried many things but I came to the conclusion:
- creating DSTs that are packed and satisfying miri is a pain
Making every struct packed would help to satisfy miri with allocations/deallocations but using packed structs in Rust is a pain for itself. Using packed DSTs is a total meltdown...
So I think, using my own Boxed-like wrapper is the best solution we can have so far. I'm 99% certain that there are no memory issues at runtime and that only miri complains under certain cirumstances.
> multiboot2: create DSTs: hopefully better memory fix

- .github/workflows/_build-rust.yml
- .github/workflows/rust.yml
- multiboot2-header/src/builder/header.rs
- multiboot2-header/src/builder/information_request.rs
- multiboot2-header/src/builder/traits.rs
- multiboot2/src/boot_loader_name.rs
- multiboot2/src/builder/information.rs
- multiboot2/src/builder/mod.rs
- multiboot2/src/command_line.rs
- multiboot2/src/lib.rs
- multiboot2/src/module.rs
- multiboot2/src/smbios.rs
> ci: run miri + adjustments for miri

- integration-test/bins/multiboot2_chainloader/src/loader.rs
- integration-test/bins/rust-toolchain.toml
- multiboot2-header/src/builder/mod.rs
- multiboot2/Changelog.md
- multiboot2/src/lib.rs
- multiboot2/src/memory_map.rs
- multiboot2/src/tag_type.rs
Support non-standard types in the memory map. We use this for example in our virtualization stack based on [Hedron](https://github.com/cyberus-technology/hedron).
Thanks to @scholzp for finding this issue.
> memory_map: support non-standard types

- multiboot2/src/end.rs
- multiboot2/src/lib.rs
- multiboot2/src/tag.rs
- multiboot2/src/tag_trait.rs
- multiboot2/src/tag_type.rs
The tag_type module was holding way too many things. Now, there are smaller modules. This should not be breaking as it is only an internal change.
> multiboot2: simplify tag_type module

- integration-test/bins/multiboot2_payload/src/verify/mod.rs
- multiboot2/Changelog.md
- multiboot2/src/lib.rs
- multiboot2/src/memory_map.rs
- multiboot2/src/module.rs
Debug output of the Multiboot2 Boot Info is now much nicer. All tags appear in alphabetical order. Example taken from the integration test:
```
Multiboot2BootInformation {
start_address: 0x1065a8,
end_address: 0x1068e8,
total_size: 0x340,
basic_memory_info: Some(
BasicMemoryInfoTag {
typ: BasicMeminfo,
size: 0x10,
memory_lower: 0x27f,
memory_upper: 0x5b80,
},
),
boot_loader_name: Some(
BootLoaderNameTag {
typ: BootLoaderName,
size: 0x12,
name: Ok(
"GRUB 2.06",
),
},
),
command_line: Some(
CommandLineTag {
typ: Cmdline,
size: 0x23,
cmdline: Ok(
"some commandline arguments",
),
},
),
efi_bs_not_exited: None,
efi_memory_map: None,
efi_sdt_32: None,
efi_sdt_64: None,
efi_ih_32: None,
efi_ih_64: None,
elf_sections (count): 0x8,
framebuffer: Some(
Ok(
FramebufferTag {
typ: Framebuffer,
size: …
```
> multiboot2: cleanup of debug format output

- .editorconfig
- .github/dependabot.yml
- .github/workflows/_build-rust.yml
- .github/workflows/integrationtest.yml
- .github/workflows/qa.yml
- .github/workflows/rust.yml
- Cargo.lock
- integration-test/bins/Cargo.lock
- integration-test/bins/multiboot2_chainloader/src/start.S
- integration-test/bins/util/Cargo.toml
- update all dependencies
- configure GitHubs dependabot
- allow GitHubs merge train feature
> modernize repository (CI, updates)

- multiboot2/Changelog.md
- multiboot2/src/builder/information.rs
Allow the builder to use custom tags. The challenge here was that `TagTrait` is not object safe, so having `Vec<dyn TagTrait>` is not an option.
This closes #168.
The builder allows to set multiple SMBios Tags but the BootInformation only allows to get one.. which one is correct?
> multiboot2: builder: allow to add custom tags

- multiboot2/src/tag.rs
The various strings in the Multiboot2 spec are specified as C-style zero-terminated strings.
Previously, if the multiboot2 crate is handed a string with non-NUL characters present between the terminating NUL (within the tag), they were returned as well.
This revision instead terminates the strings on the first NUL character, as would be typical in C handling. Although unterminated strings in Multiboot2 are technically an error, current unterminated string behavior is maintained.
> multiboot2: Follow C behavior for string parsing

- .github/workflows/rust.yml
- Cargo.lock
- integration-test/bins/Cargo.lock
- multiboot2/Cargo.toml
- multiboot2/Changelog.md
- multiboot2/README.md
- multiboot2/src/boot_loader_name.rs
- multiboot2/src/builder/boxed_dst.rs
- multiboot2/src/command_line.rs
- multiboot2/src/lib.rs
- multiboot2/src/module.rs
- multiboot2/src/tag.rs
This is a follow-up of #172.
A new `StringError` error type was introduced and the MSRV is bumped from `1.68` to `1.69`.
FYI: Ping @A0lson
> string parsing followup: introduce better fitting error type + raise MSRV

- multiboot2-header/Cargo.toml
Currently, when using multiboot2-header with no alloc (default-features = false), you wil get `error: no global memory allocator found but one is required` error.  Reason being , when including multiboot2 for MBI tags, it will also include alloc and builder. This patch fixes that so that you can use multiboot2-header as intended without alloc when it is off.
> updating header to not include multiboot with alloc

- .github/dependabot.yml
- Cargo.lock
- integration-test/bins/Cargo.lock
- multiboot2-header/Cargo.toml
- multiboot2-header/Changelog.md
- multiboot2-header/README.md
- multiboot2-header/src/lib.rs
> prepare release multiboot2-header-v0.3.2

- Cargo.lock
- integration-test/bins/multiboot2_chainloader/src/multiboot.rs
- integration-test/bins/multiboot2_payload/src/verify/grub.rs
- integration-test/bins/rust-toolchain.toml
- integration-test/bins/x86-unknown-none.json
- integration-test/nix/sources.json
- integration-test/tests/multiboot2/build_img.sh
- multiboot2-header/Cargo.toml
- multiboot2-header/Changelog.md
- multiboot2-header/src/end.rs
- multiboot2-header/src/header.rs
- multiboot2/Cargo.toml
- multiboot2/Changelog.md
- multiboot2/src/builder/information.rs
- multiboot2/src/efi.rs
- multiboot2/src/image_load_addr.rs
- multiboot2/src/memory_map.rs
- multiboot2/src/rsdp.rs
- fix CI
- modernize / updates
> misc: various improvements

- multiboot2/src/builder/information.rs
Some devices have multiple major versions of SMBIOS, say 2 and 3, and I want to pass them all and let the OS decide which one to use.
The standard doesn't explicitly state something along the lines of "this tag may occur multiple times", but it also doesn't specify that tags may occur just once, so I'm not sure, if this makes sense.
This used to work before https://github.com/rust-osdev/multiboot2/commit/3956403ee64e7e348e94df7ec44962ef97c9c9cd.
> multiboot2: builder: Allow to specify SMBIOS tag multiple times

- Cargo.lock
- integration-test/bins/Cargo.lock
- multiboot2/Cargo.toml
- multiboot2/Changelog.md
- multiboot2/src/lib.rs
- multiboot2/src/memory_map.rs
- multiboot2/src/module.rs
- multiboot2/src/tag_trait.rs
> multiboot2: fix handling of efi memory map

- multiboot2/CHANGELOG.md
- multiboot2/src/apm.rs
- multiboot2/src/bootdev.rs
- multiboot2/src/builder.rs
- multiboot2/src/end.rs
- multiboot2/src/lib.rs
- multiboot2/src/network.rs
> multiboot2: add missing tags

- multiboot2-header/Cargo.toml
Looks like for package in a subdirectory of a repo there is no better way then linking to "tree/main"
The alternative would be to get rid of `homepage` key completely.
> Replaces dead link home page multiboot2-header package definition

- multiboot2/CHANGELOG.md
- multiboot2/src/boot_information.rs
Closes #212 and follow-up of #100.
> multiboot2: streamline getters and public tags()

- integration-test/bins/multiboot2_payload/src/verify/mod.rs
- multiboot2/CHANGELOG.md
- multiboot2/src/apm.rs
- multiboot2/src/boot_information.rs
- multiboot2/src/bootdev.rs
- multiboot2/src/builder.rs
- multiboot2/src/elf_sections.rs
- multiboot2/src/end.rs
- multiboot2/src/lib.rs
This fixes #243 and probably also #244
> multiboot2: bug fixes
